// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyKhronus.DataAccess.Context;

#nullable disable

namespace MyKhronus.DataAccess.Migrations.MyKhronus
{
    [DbContext(typeof(MyKhronusContext))]
    [Migration("20260506181003_v_0.1.0")]
    partial class v_010
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("mk")
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyKhronus.DataAccess.Entities.Activity", b =>
                {
                    b.Property<Guid>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActivityId");

                    b.ToTable("Activity", "mk");
                });

            modelBuilder.Entity("MyKhronus.DataAccess.Entities.ActivityRecord", b =>
                {
                    b.Property<Guid>("ActivityRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ActivityRecordId");

                    b.HasIndex("ActivityId");

                    b.ToTable("ActivityRecord", "mk");
                });

            modelBuilder.Entity("MyKhronus.DataAccess.Entities.DayEntry", b =>
                {
                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.HasKey("EntryDate", "WorkItemId");

                    b.ToTable("DayEntry", "mk");
                });

            modelBuilder.Entity("MyKhronus.DataAccess.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Project", "mk");
                });

            modelBuilder.Entity("MyKhronus.DataAccess.Entities.WorkItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DayEntryEntryDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DayEntryWorkItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUsed")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("DayEntryEntryDate", "DayEntryWorkItemId");

                    b.ToTable("WorkItem", "mk");
                });

            modelBuilder.Entity("MyKhronus.DataAccess.Entities.ActivityRecord", b =>
                {
                    b.HasOne("MyKhronus.DataAccess.Entities.Activity", "Activity")
                        .WithMany("Records")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("MyKhronus.DataAccess.Entities.WorkItem", b =>
                {
                    b.HasOne("MyKhronus.DataAccess.Entities.Project", "Project")
                        .WithMany("WorkItems")
                        .HasForeignKey("ProjectId");

                    b.HasOne("MyKhronus.DataAccess.Entities.DayEntry", null)
                        .WithMany("WorkItem")
                        .HasForeignKey("DayEntryEntryDate", "DayEntryWorkItemId");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("MyKhronus.DataAccess.Entities.Activity", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("MyKhronus.DataAccess.Entities.DayEntry", b =>
                {
                    b.Navigation("WorkItem");
                });

            modelBuilder.Entity("MyKhronus.DataAccess.Entities.Project", b =>
                {
                    b.Navigation("WorkItems");
                });
#pragma warning restore 612, 618
        }
    }
}
